title: redesigned memory
author:
  name: name name
  orcid: 

tagline: minima-based design endeavour
description: >
  Lorem ipsum


# Build settings
baseurl: ""
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag




sass:
  quiet_deps: true
  silence_deprecations: [import]


minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  # nav_pages:
  #   - pages/about.md
  #   - categories.md
  #   - resources.md
  #   - critical-ai-scholars.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: false

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  date_format: "%A, %B %d, %Y"

  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.




# COLLECTIONS and DEFAULT settings ## TS ##

collections:
  pages:
    output: true
    permalink: /:name/



defaults:
  -
    scope:
      path: "pages" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "posts" # an empty string here means all files in the project
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"





# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/